# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClanInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x43lanInfo.proto\x12\x08\x43lanData\"\"\n\x0f\x43lanInfoRequest\x12\x0f\n\x07\x63lan_id\x18\x01 \x01(\x04\"\xe7\x02\n\x10\x43lanInfoResponse\x12\x0f\n\x07\x63lan_id\x18\x01 \x01(\x04\x12\x11\n\tclan_name\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\r\x12\x12\n\ncaptain_id\x18\x04 \x01(\x04\x12\x12\n\nclan_level\x18\x05 \x01(\r\x12\x13\n\x0bmax_members\x18\x06 \x01(\r\x12\x17\n\x0f\x63urrent_members\x18\x07 \x01(\r\x12\x16\n\x0ejoin_level_req\x18\x08 \x01(\r\x12\x15\n\rapproval_type\x18\t \x01(\r\x12\x0e\n\x06region\x18\r \x01(\t\x12\x11\n\tclan_tags\x18\x0e \x01(\t\x12\x10\n\x08officers\x18\x0f \x01(\t\x12\x13\n\x0btotal_glory\x18\x10 \x01(\r\x12\x1a\n\x12timestamp_update_1\x18\x12 \x01(\r\x12\x1a\n\x12timestamp_update_2\x18\x13 \x01(\r\x12\x14\n\x0cseason_glory\x18\x14 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ClanInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLANINFOREQUEST._serialized_start=28
  _CLANINFOREQUEST._serialized_end=62
  _CLANINFORESPONSE._serialized_start=65
  _CLANINFORESPONSE._serialized_end=424
# @@protoc_insertion_point(module_scope)
